```{r setup, include=FALSE} knitr::opts_chunk$set(echo = TRUE) ``` ### R Markdown Both R and Python have libraries that can process files referred to as "shape files". Details on the definition and development of the format can be read at [wikipedia] (<https://en.wikipedia.org/wiki/Shapefile>). An important thing to know is that whereas shape file refers to data that is used to represent geographical features, it needs 3 files to be operational. ### .shp where coordinates of geographical features are kept. ### .shx an indexing file for geometric features. ### .dbf data that is associated with the geometric features. The folder we are going to download exists within the US Census Bureau website. From the website we navigate to where the [shape files for all the counties in USA are located](https://www2.census.gov/geo/tiger/TIGER2021/COUNTY/) As you can see from the download, there are additional files present besides the .shp, .shx and .dbf. These are files that are not required for R and Python to create informative maps but we will keep them in our folder. In this project we make use of a multitude of spatial tools and functions for statistical analysis but for now we will focus only on the mapping aspects and the simple features, [sf package](https://r-spatial.github.io/sf/). ```{r} # Loading the library, if you are using Windows you will have to make sure you have Rtools before being able to use the library --> library(sf) #We downloaded the shape zip folder, unzipped all the files in it to the data folder and read it in with the read_sf command--> shape <- read_sf(dsn = "C:/Users/rm84/Desktop/research/HMM/data/tl_2021_us_county.shp") #as can be seen from the dim command you have 3234 observations (counties) and 18 features associated with each county dim(shape) #In R, objects have attributes. The shape object has 5 of these length(attributes(shape)) #We will look at only the first attribute's values attributes(shape)[1] #Names function will give us the values in the first attribute names(shape) #We will be working with only the Californian state #selecting California via FIPS state code as you can see selection is done via base R via the %in% statement shape=shape[(shape$STATEFP %in% '06'),] #We could look at a very simple set of plots plot(shape) #The shape function has 17 attributes and R chooses to plot a smaller number of them to fit the screen. #We would rather do something a bit more useful and plot one of the attributes we are interested in plot(shape[15]) #Note that if you wrote plot(shape$AWATER) you get a scatterplot. ``` A good [vignette](https://r-spatial.github.io/sf/articles/) exists to explain the sf package. Before we introduce better looking plots we need to understand how to merge data to a shapefile. We created a dataframe named \bold{CASummary} by wrangling through a multitude of datasets which will be discussed on a later post. It is important to look at some of the output from this dataset. ```{r include=TRUE} library(sf) library(ggpubr) library(cowplot) library(viridis) library(ggplot2) library(ggspatial) library(stringr) #The shape file for the counties of United States shape <- read_sf(dsn = "C:/Users/rm84/Desktop/research/HMM/data/tl_2021_us_county.shp") #Get California shape=shape[(shape$STATEFP %in% '06'),] #There are pages of multiple scripts to create this data-frame this will be uploaded to github later. #For the sake of presentation this was exported as a csv file data_for_spatial=read.table(header=TRUE,sep=',','C:/Users/rm84/Documents/data_for_spatial.csv') poverty_for_spatial=read.table(header=TRUE,sep=',','C:/Users/rm84/Documents/poverty_for_spatial.csv') #Leading 0s are erased by default which creates a problem for County Identifiers since they will be matched to the same set of values under another name in the Spatial file. data_for_spatial$ID=str_sub(paste0('00',data_for_spatial$ID),-3) #Each of the 58 counties of California in alphabetical and FIPS order have 164 columns of information associated with it. The last 154 columns represent 2 sets of variables across a 77 biweek time period. Mortality and Vaccinations Rates. dim(data_for_spatial) #First 10 values in the data.frame object # names(data_for_spatial)[1:10] #identify the unique keys in each object. shape and #CASUmmary has 58 unique GEOID and ID values representing #the counties in California They are 3 digit FIPS codes. #001 003 etc... #it is important to first write the shape file otherwise you end up with a data frame shapeanddata=merge(shape,data_for_spatial,by.x="COUNTYFP",by.y="ID") #This is needed to unnormalize the poverty percentages meanpov=mean(poverty_for_spatial[,5]) sdpov=sd(poverty_for_spatial[,5]) #_spatial options require ggspatial package operations on data are allowed. In this instance we used to unnormalize the poverty variable map_Pov20=ggplot() + annotation_spatial(shapeanddata) + layer_spatial(shapeanddata, aes(fill = (Poverty20*sdpov+meanpov)))+ labs(fill = "Pov. 20") #We can create a simple plot that shows the poverty rates in 2020 map_Pov20 map_Pov21=ggplot() + annotation_spatial(shapeanddata) + layer_spatial(shapeanddata, aes(fill = (Poverty21*sdpov+meanpov)))+ labs(fill = "Pov. 21") #Different scales we need to put them on the same scale plot_grid(map_Pov20,map_Pov21) ######################################### #Let us hide the legend and use a common scale for these two years. Since we remove the legend from map_Pov20 the plot does not look good when put side by side even though the scales are the same. Note how the direction -1 specifies the color scale reversal. map_Pov20=ggplot() + annotation_spatial(shapeanddata) + layer_spatial(shapeanddata, aes(fill = (Poverty20*sdpov+meanpov)))+ labs(fill = "Pov. 20")+scale_fill_viridis(limits = c(0,22),direction=-1)+ theme(legend.position = "none",plot.title =element_blank()) map_Pov21=ggplot() + annotation_spatial(shapeanddata) + layer_spatial(shapeanddata, aes(fill = (Poverty21*sdpov+meanpov)))+ labs(fill = "Pov. 21")+scale_fill_viridis(limits = c(0,22),direction=-1) plot_grid(map_Pov20,map_Pov21) ``` We can do better by using the ggpubr library.Furthermore annotating the map allows us to highlight counties such as Merced which has its Poverty percentage increase from 2020 to 2021. We have hard coded the label and its coordinates which is not ideal and opens room for error. ```{r} map_Pov20=ggplot() + annotation_spatial(shapeanddata) + layer_spatial(shapeanddata, aes(fill = (Poverty20*sdpov+meanpov)))+ theme(legend.title= element_blank())+ labs(fill = "Pov. 20")+scale_fill_viridis(limits = c(0,22),direction=-1) map_Pov21=ggplot() + annotation_spatial(shapeanddata) + layer_spatial(shapeanddata, aes(fill = (Poverty21*sdpov+meanpov)))+annotate("text", x = -118, y =40 , label = "Merced")+ annotate("segment", color="red", x=-118, xend = -120.5, y=39.8, yend=37.2, arrow=arrow(length=unit(0.2,"cm")))+xlab("")+ylab("")+ labs(fill = "Pov. 21")+scale_fill_viridis(limits = c(0,22),direction=-1) map_Pov2021 <- ggarrange(labels=c("Poverty 2020","Poverty 2021"),map_Pov20, map_Pov21, nrow=1, align="h", common.legend = TRUE) annotate_figure(fig.lab.face="bold",fig.lab.size=14,fig.lab.pos="top.left",map_Pov2021, fig.lab = "Maps of Poverty Percentages") ``` ```{r} library(tidyr) library(dplyr) VacPop=read.table('C:/Users/rm84/Documents/VacPop.csv',header = TRUE,sep=",") names=sort(shape$NAMELSAD) gvacPop1=as.data.frame(cbind(names,VacPop)) names(gvacPop1)[1]="names" names(gvacPop1)[2]="fips" T=ncol(VacPop)-1 for(c in 1:(T)){ names(gvacPop1)[c+2]=paste0("Time_",c) } gvacPop2=gvacPop1 %>% pivot_longer( cols = starts_with("Time"), names_to = "Time", values_to = "Vac", values_drop_na = TRUE ) head(gvacPop2) gvacPop2=select(gvacPop2, -c(fips)) gvacPop2=as.data.frame(gvacPop2) head(gvacPop2) #Create a numerical time index for the 58 counties in California, recall T is 77 gvacPop2$Time=rep(c(1:T),58) #First 6 rows of the dataset gvacPop2 head(gvacPop2) ################################## maxtime=ncol(VacPop)-1 labels = data.frame(Vac = as.numeric(gvacPop1[which(gvacPop1[,maxtime+1]==max(gvacPop1[,maxtime+1])), maxtime+1])+0.02,Time = maxtime,text = paste0(names[which(gvacPop1[,maxtime]==min(gvacPop1[,maxtime]))])) gvacPop2$Vac=as.numeric(gvacPop2$Vac) maxlabel = data.frame(Vac = as.numeric(gvacPop1[which(gvacPop1[,maxtime+1]==max(gvacPop1[,maxtime+1])), maxtime+1])+0.02, Time = maxtime,text = paste0(names[which(gvacPop1[,maxtime+1]==max(gvacPop1[,maxtime+1]))])) #minlabel and maxlabel are created in order to demonstrate how to partially parameterize the annotations on the ggplot. minlabel will have the information regarding the county with the least amount of vaccination. maxlabel will have the information regarding the county with the most amount of vaccination minlabel = data.frame(Vac = as.numeric(gvacPop1[which(gvacPop1[,maxtime+1]==min(gvacPop1[,maxtime+1])), maxtime+1])+0.02,Time = maxtime,text = paste0(names[which(gvacPop1[,maxtime]==min(gvacPop1[,maxtime]))])) i3=ggplot(gvacPop2, aes(x = Time, y = Vac,color=names)) + geom_line()+ theme(legend.position = "none")+ theme(axis.title.y =element_blank())+ xlab("Biweek t")+ annotate("text", x = maxtime-15, y = maxlabel[,1], label =maxlabel[,3])+ annotate("segment", color="blue", x=maxtime-2, xend = maxtime-7, y=maxlabel[,1], yend=maxlabel[,1], arrow=arrow(length=unit(0.2,"cm")))+ annotate("text", x = maxtime-15, y = minlabel[,1], label = minlabel[,3])+ annotate("segment", color="blue", x=maxtime-2, xend = maxtime-7, y=minlabel[,1], yend=minlabel[,1], arrow=arrow(length=unit(0.2,"cm")))+ ggtitle("Percent of Population Vaccinated")+ theme(plot.title = element_text(hjust = 0.5)) i3 ```